### ISSUE TITLE
share example of working source pascal code

### ISSUE THREAD

**Issue by Uladzislau-Lesneuski** [dfdemar/Pascal_Interpreter#1]
Hi, I'll hope, author will notice this issue message. I wanna to know more about this your application, pls add me to skype - vlad25722

**Comment by dfdemar** [comment]
Hi, this project is unfinished but you can find the complete source code in Java from Writing Compilers and Interpreters by Ronald Mak.

**Comment by Uladzislau-Lesneuski** [comment]
Maybe do u have this book in pdf format or smth like that

**Comment by dfdemar** [comment]
You can buy a digital copy on Amazon.
